#ifndef OPTIMISATION_D_UNE_LIGNE_D_ASSEMBLAGE_TD12GRP3_HEADER1_H
#define OPTIMISATION_D_UNE_LIGNE_D_ASSEMBLAGE_TD12GRP3_HEADER1_H

typedef struct {
    int num;
    int * tab;
} Station;
void afficherExclusions();


#endif //OPTIMISATION_D_UNE_LIGNE_D_ASSEMBLAGE_TD12GRP3_HEADER1_H
